config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Regular HTML routes
  get "home", to: "home#index", as: "home"
  get "home/about", to: "home#about", as: "about"
  # get "error_404", to: "errors#not_found", as: "error_404"

  # Session management routes
  resources :sessions, only: [ :new, :create, :destroy ]
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  resources :users
  resources :media, except: [ :destroy ]
  resources :characters, except: [ :destroy ]
  resources :items
  resources :user_items, except: [ :show ]
  resources :user_media, except: [ :show, :edit, :update ]
  resources :user_characters, except: [ :show, :edit, :update ]
  resources :character_items, only: [ :new, :create, :destroy ]

  # Defines the root path route ("/")
  root "home#index"
end

app/models/user_character.rb
class UserCharacter < ApplicationRecord
  # Relationships
  belongs_to :user
  belongs_to :character

  # Validations
  validates_presence_of :user_id
  validates_presence_of :character_id
  validate :character_is_not_a_duplicate, on: :create

  def already_exists?
    UserCharacter.where(user_id: self.user_id, character_id: self.character_id).size == 1
  end

  private
  def character_is_not_a_duplicate
    return true if self.user_id.nil? || self.character_id.nil?
    if self.already_exists?
      character = Character.find_by(id: self.character_id)
      errors.add(:character_id, "You've already saved #{character.name}!")
    end
  end
end

app/controllers/user_characters_controller.rb
class UserCharactersController < ApplicationController
  before_action :set_user_character, only: [ :destroy ]
  authorize_resource

  # GET /user_characters or /user_characters.json
  def index
    @user_characters = UserCharacter.where(user_id: current_user.id)
  end

  # GET /user_characters/new
  def new
    @user_character = UserCharacter.new(character_id: params[:character_id])
  end

  # POST /user_characters or /user_characters.json
  def create
    @user_character = UserCharacter.new(user_character_params)
    @user_character.user = current_user

    if @user_character.save
      redirect_to user_characters_path, notice: "Character was successfully added to your saves."
    else
      render :new
    end
  end

  # DELETE /user_characters/1 or /user_characters/1.json
  def destroy
    @user_character.destroy
    redirect_to user_characters_path, notice: "Saved character was successfully removed."
  end

  private
  def set_user_character
    @user_character = UserCharacter.find(params[:id])
  end

  def user_character_params
    params.require(:user_character).permit(:character_id, :purchased, :rating, :review)
  end
end

app/helpers/user_characters_helper.rb
module UserCharactersHelper
  def get_character_options(user = current_user)
    return [] unless user

    saved_characters = user.user_characters.select(:character_id)
    Character.alphabetical.where.not(id: saved_characters).includes(:medium).map { |c| [ "#{c.name} (#{c.medium.name})", c.id ] }
  end
end

app/views/user_characters/_fields.html.erb
<% if @user_character && @user_character.character_id %>
    <%= f.input :character_id, collection: get_character_options, include_blank: false, selected: @user_character.character_id, input_html: { class: 'browser-default' } %>
<% else %>
    <%= f.input :character_id, collection: get_character_options, include_blank: true, input_html: { class: 'browser-default' } %>
<% end %>

app/views/user_characters/_user_characters_list.html.erb
<% if @user_characters.any? %>
    <h4>Saved Characters</h4>
    <% for user_character in @user_characters %>
        <div class="col s4">
            <div class="card small">
                <div class="card-image list_card" style="overflow: visible;">
                    <div class="img_card_wrapper">
                        <% if user_character.character.image.attached? %>
                            <%= image_tag user_character.character.image, class: "list_img" %>
                        <% else %>
                            <%= image_tag "photo_placeholder.jpg", class: "list_img" %>
                        <% end %>
                    </div>
                    <%= button_to user_character_path(user_character), method: :delete, data: { turbo_confirm: 'Are you sure you wish to delete this information?' }, class: "btn-floating halfway-fab waves-effect waves-light red" do %>
                            <i class="material-icons trash_icon">delete</i>
                    <% end %>
                </div>
                <div class="card-content">
                    <span class="card-title"><%= link_to truncate(user_character.character.name, length: 22, omission: "..."), character_path(user_character.character) %></span>
                    <p><%= user_character.character.medium.name %></p>
                </div>
            </div>
        </div>
    <% end %>
<% else %>
    <h4>You have no saved characters yet! :0</h4>
<% end %>

app/views/user_characters/index.html.erb
<%= render partial: "partials/card_index_structure", locals: {model_name: "user_character", 
                                                       primary: "user_characters_list",
                                                       not_save: false,
                                                       filters: false,
                                                       filter_page: ""} %>

app/views/user_characters/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @user_character, 
                                                        type_of_form: "New Saved Character",
                                                        fields: "user_characters/fields"} %>