config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Regular HTML routes
  get "home", to: "home#index", as: "home"
  get "home/about", to: "home#about", as: "about"
  # get "error_404", to: "errors#not_found", as: "error_404"

  # Session management routes
  resources :sessions, only: [ :new, :create, :destroy ]
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  resources :users
  resources :media, except: [ :destroy ]
  resources :characters, except: [ :destroy ]
  resources :items
  resources :user_items, except: [ :show ]
  resources :user_media, except: [ :show, :edit, :update ]
  resources :user_characters, except: [ :show, :edit, :update ]
  resources :character_items, only: [ :new, :create, :destroy ]

  # Defines the root path route ("/")
  root "home#index"
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-pink btn") do %>
    <strong>Add a New <%= model_name == "medium" ? "Media" : model_name.humanize %></strong>
  <% end %>

app/views/partials/_admin_nav.html.erb
<nav id="nav">
  <div class="container nav-container">
    <ul class="left hide-on-med-and-down">
        <%# Users can see their account, items, media, and characters %>
        <li class="nav_item"><%= link_to 'Items', items_path %></li>
        <li class="nav_item"><%= link_to 'Characters', characters_path %></li>
        <li class="nav_item"><%= link_to 'Media', media_path %></li>
        <li class="nav_item"><%= link_to 'Manage Users', users_path %></li>
    </ul>
    <ul class="hide-on-large-only">
        <li class="nav_item" id="hamburger-toggle"><i class="material-icons">menu</i></li>
    </ul>
    <ul class="right">
        <div class="dropdown">
          <li class="dropdown_btn nav_item" id="dropdown_trigger">
            <%= current_user.username %>
            <i class="material-icons" id="dropdown_caret">arrow_drop_down</i>
          </li>
          <div id="dropdown_content">
            <li id="profile_tab"><%= link_to 'My Profile', user_path(current_user), class: "dropdown_link" %></li>
            <li><%= link_to 'Saved Items', user_items_path, class: "dropdown_link" %></li>
            <li><%= link_to 'Saved Characters', user_characters_path, class: "dropdown_link" %></li>
            <li><%= link_to 'Saved Media', user_media_path, class: "dropdown_link" %></li>
            <li id="logout_tab"><%= link_to 'Logout', logout_path, class: "dropdown_link" %></li>
          </div>
        </div>
    </ul>
  </div>
</nav>
<ul class="hide-on-large-only" id="hamburger-container">
  <div class="hamburger-content hide-on-large-only" id="hamburger-content">
      <li class="nav_item"><%= link_to 'Items', items_path, class: "hamburger-item" %></li>
      <li class="nav_item"><%= link_to 'Characters', characters_path, class: "hamburger-item" %></li>
      <li class="nav_item"><%= link_to 'Media', media_path, class: "hamburger-item" %></li>
      <li class="nav_item"><%= link_to 'Manage Users', users_path, class: "hamburger-item" %></li>
  </div>
</ul>

app/views/partials/_card_index_structure.html.erb
<div class="list_head">
    <% if not_save %>
        <h4><%= model_name.pluralize.capitalize %></h4>
    <% end %>
    <!-- Add a button for new instances of object -->
    <% if logged_in? and not_save %>
    <%= render :partial => 'partials/add_new_object', locals: {model_name: model_name} %>
    <% end %>
    <% if filters %>
        <%= render partial: "#{filter_page}", locals: {model_name: model_name} %>
    <% end %>
</div>

<div>
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
</div>

app/views/partials/_card_show_structure.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
  </div>
  <div class="col s4">
    <!-- space -->
    <p>&nbsp;</p>
  </div>
</div>
<div class="row">
  <%= render :partial => 'partials/display_base_errors', locals: {object: object} %>
  <div class="list_head">
    <%= render :partial => 'partials/object_options', locals: {model_name: model_name, object: object} %>
  </div>
</div>
<%= render :partial => "#{association_card}", locals: {object: object} %>

app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to 'About Find a Cosplay', about_path %><br />
  <div id="copy">
    Webmaster: &nbsp;&nbsp;<%= mail_to("stephanie.reed.3026@gmail.com", "Stephanie Reed", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2026
  </div>

</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object, data: { turbo: false }) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
            </div>
          </div>
          <p>&nbsp;</p>
          <div class="row">
            <div class="form-actions col s9">
              <%= f.button :submit, 'Submit', class: "waves-effect waves-pink btn" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_guest_nav.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
        <%# Guests only see items, characters, media and create an account %>
        <li class="nav_item"><%= link_to 'Items', items_path %></li>
        <li class="nav_item"><%= link_to 'Characters', characters_path %></li>
        <li class="nav_item"><%= link_to 'Media', media_path %></li>
        <li class="nav_item"><%= link_to "Create an Account", new_user_path %></li>
    </ul>
    <ul class="hide-on-large-only">
        <li class="nav_item" id="hamburger-toggle"><i class="material-icons">menu</i></li>
    </ul>
    <ul class="right">
      <li class="nav_item">
        <%= link_to 'Login', login_path %>
      </li>
    </ul>
  </div>
</nav>
<ul class="hide-on-large-only" id="hamburger-container">
  <div class="hamburger-content hide-on-large-only" id="hamburger-content">
      <li class="nav_item"><%= link_to 'Items', items_path, class: "hamburger-item" %></li>
      <li class="nav_item"><%= link_to 'Characters', characters_path, class: "hamburger-item" %></li>
      <li class="nav_item"><%= link_to 'Media', media_path, class: "hamburger-item" %></li>
      <li class="nav_item"><%= link_to "Create an Account", new_user_path, class: "hamburger-item" %></li>
  </div>
</ul>

app/views/partials/_index_structure.html.erb
<!-- Add a button for new instances of object -->
<% if logged_in? and not_save %>
  <%= render :partial => 'partials/add_new_object', locals: {model_name: model_name} %>
<% end %>

<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="col s1">
    <!-- space -->
    <p>&nbsp;</p>
  </div>
  <div class="col s3">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

app/views/partials/_nav.html.erb
<nav id="nav">
  <div class="container nav-container">
    <ul class="left hide-on-med-and-down">
        <%# Users can see their account, items, media, and characters %>
        <li class="nav_item"><%= link_to 'Items', items_path %></li>
        <li class="nav_item"><%= link_to 'Characters', characters_path %></li>
        <li class="nav_item"><%= link_to 'Media', media_path %></li>
    </ul>
    <ul class="hide-on-large-only">
        <li class="nav_item" id="hamburger-toggle"><i class="material-icons">menu</i></li>
    </ul>
    <ul class="right">
        <div class="dropdown">
          <li class="dropdown_btn nav_item" id="dropdown_trigger">
            <%= current_user.username %>
            <i class="material-icons" id="dropdown_caret">arrow_drop_down</i>
          </li>
          <div id="dropdown_content">
            <li id="profile_tab"><%= link_to 'My Profile', user_path(current_user), class: "dropdown_link" %></li>
            <li><%= link_to 'Saved Items', user_items_path, class: "dropdown_link" %></li>
            <li><%= link_to 'Saved Characters', user_characters_path, class: "dropdown_link" %></li>
            <li><%= link_to 'Saved Media', user_media_path, class: "dropdown_link" %></li>
            <li id="logout_tab"><%= link_to 'Logout', logout_path, class: "dropdown_link" %></li>
          </div>
        </div>
    </ul>
  </div>
</nav>
<ul class="hide-on-large-only" id="hamburger-container">
  <div class="hamburger-content hide-on-large-only" id="hamburger-content">
      <li class="nav_item"><%= link_to 'Items', items_path, class: "hamburger-item" %></li>
      <li class="nav_item"><%= link_to 'Characters', characters_path, class: "hamburger-item" %></li>
      <li class="nav_item"><%= link_to 'Media', media_path, class: "hamburger-item" %></li>
  </div>
</ul>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.humanize }" %>

<div class="form-actions">
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-pink btn') do %>
      &nbsp;Display All
    <% end %>
    &nbsp;&nbsp;
  
  <% if controller.respond_to?(:update) && can?(:update, object) %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-pink btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if controller.respond_to?(:destroy) && can?(:destroy, object) %>
    <% if model_name == "user" && object.username == "admin"%>
      <%# Prevent deletion of admin user %>
      <p>Cannot delete original admin user. Contact dev if this is a mistake.</p>
    <% elsif model_name != "item" %>
      <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-pink btn btn-alert') do %>
          &nbsp;<%= "Delete #{opt}" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s1">
    <!-- space -->
    <p>&nbsp;</p>
  </div>
  <div class="col s3">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<div class="row">
  <%= render :partial => 'partials/display_base_errors', locals: {object: object} %>
  <%= render :partial => 'partials/object_options', locals: {model_name: model_name, object: object} %>
</div>

app/views/partials/_topbar.html.erb
<div class="row valign-wrapper" id="topbar">
    <%= link_to home_path do %>
        <%= image_tag "banner.jpg", alt: "Find a Cosplay banner", id: "topbar_banner" %>
    <% end %>
</div>