config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Regular HTML routes
  get "home", to: "home#index", as: "home"
  get "home/about", to: "home#about", as: "about"
  # get "error_404", to: "errors#not_found", as: "error_404"

  # Session management routes
  resources :sessions, only: [ :new, :create, :destroy ]
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  resources :users
  resources :media, except: [ :destroy ]
  resources :characters, except: [ :destroy ]
  resources :items
  resources :user_items, except: [ :show ]
  resources :user_media, except: [ :show, :edit, :update ]
  resources :user_characters, except: [ :show, :edit, :update ]
  resources :character_items, only: [ :new, :create, :destroy ]

  # Defines the root path route ("/")
  root "home#index"
end

app/models/character.rb
class Character < ApplicationRecord
  include Helpers::Deletions

  # Relationships
  has_many :user_characters
  has_many :users, through: :user_characters
  has_many :character_items
  has_many :items, through: :character_items
  belongs_to :medium
  has_one_attached :image

  # Enum for hair length
  enum :hair_length, { short: 1, bob: 2, medium: 3, long: 4, none: 5 }, scopes: true, suffix: true

  # For role dropdown
  HAIR_LENGTHS = [ [ "Short", "short" ], [ "Bob", "bob" ], [ "Medium", "medium" ], [ "Long", "long" ], [ "None", "none" ] ]

  # Scopes
  scope :alphabetical, -> { order(:name) }
  scope :for_medium, ->(medium_id) { where("medium_id = ?", medium_id) }
  scope :with_hair_length, ->(length) { where("hair_length = ?", hair_lengths[length]) }
  scope :with_hair_color, ->(color) { where("hair_color ILIKE ?", "%#{color}%") }
  scope :with_eye_color, ->(color) { where("eye_color ILIKE ?", "%#{color}%") }
  scope :search, ->(term) { where("characters.name ILIKE ?", "%#{term}%").order("characters.name") }

  # Validations
  validates_presence_of :name
  validates_presence_of :medium_id
  validate :character_is_not_a_duplicate, on: :create

  def already_exists?
    Character.where(name: self.name, medium_id: self.medium_id).size == 1
  end

  # Callbacks
  before_validation :strip_name
  before_destroy :cannot_destroy_object

  # Methods
  def hair_type
    if hair_length == "none"
      "No hair"
    elsif hair_length == "bob"
      hair_color + " " + hair_length
    else
      hair_length + ", " + hair_color + " hair"
    end
  end

  private
  def strip_name
    self.name = name&.strip
  end

  def character_is_not_a_duplicate
    return true if self.name.nil? || self.medium_id.nil?
    if self.already_exists?
      medium = Medium.find_by(id: self.medium_id)
      errors.add(:name, "This character (#{self.name}, from the #{medium.media_type} #{medium.name}) already exists in the system!")
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [ :show, :edit, :update ]
  before_action :check_login, only: [ :new, :create, :edit, :update ]
  authorize_resource

  # GET /characters
  def index
    @characters = Character.alphabetical
    if params[:query].present?
      @characters = @characters.search(params[:query])
    end
    if params[:hair_length].present?
      @characters = @characters.with_hair_length(params[:hair_length])
    end
    if params[:hair_color].present?
      @characters = @characters.with_hair_color(params[:hair_color])
    end
    if params[:eye_color].present?
      @characters = @characters.with_eye_color(params[:eye_color])
    end
  end

  # GET /characters/1
  def show
    @is_saved = false
    if current_user
      @is_saved = current_user.characters.exists?(@character.id)
      @user_character = current_user.user_characters.find_by(character_id: @character.id)
    end
    @added_items = @character.items.joins(:character_items).distinct.select("items.*, character_items.id as character_item_id").alphabetical
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to character_path(@character), notice: "Character was successfully created in the system."
    else
      render :new
    end
  end

  # PATCH/PUT /characters/1
  def update
    if @character.update(character_params)
      redirect_to character_path(@character), notice: "#{@character.name} was successfully updated in the system."
    else
      render :edit
    end
  end

  private
  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:name, :medium_id, :image, :hair_color, :hair_length, :eye_color)
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
  # helper to pull the list of media for the character form dropdown
  def get_media_options
    Medium.alphabetical.map { |m| [ m.name, m.id ] }
  end
end

app/views/characters/_character_data.html.erb
<div class="card">
    <div class="card-content">
        <% if @character.image.attached? %>
            <%= image_tag @character.image, class: "data-img" %>
        <% end %>
        <h4><%= @character.name %> (<%= link_to "#{@character.medium.name}", medium_path(@character.medium) %>)</h4><br />
        <b>Hair Length: <%= @character.hair_length.capitalize %></b><br />
        <b>Hair Color: <%= @character.hair_color %></b><br />
        <b>Eye Color: <%= @character.eye_color %></b><br />
        <p>&nbsp;</p>
        <% if @is_saved %>
            <%= button_to user_character_path(@user_character), method: :delete, data: { turbo_confirm: 'Are you sure you wish to delete this information?' }, class: 'waves-effect waves-pink btn btn-alert' do %>
                <b>Remove from Saves</b>
            <% end %>
        <% elsif logged_in? %>
            <b><%= button_to 'Save This Character', new_user_character_path, method: :get, params: { character_id: @character.id }, class: 'waves-effect waves-pink btn' %></b><br />
        <% end %>
    </div>
</div>

app/views/characters/_characters_list.html.erb
<% if @characters.any? %>
    <% for character in @characters %>
    <div class="col s4">
        <div class="card small">
            <div class="card-image list_card">
                <% if character.image.attached? %>
                    <%= image_tag character.image, class: "list_img" %>
                <% else %>
                    <%= image_tag "photo_placeholder.jpg", class: "list_img" %>
                <% end %>
            </div>
            <div class="card-content">
                <span class="card-title"><%= link_to truncate(character.name, length: 22, omission: "..."), character_path(character) %></span>
                <p><%= link_to truncate(character.medium.name, length: 22, omission: "..."), medium_path(character.medium) %></p>
            </div>
        </div>
    </div>
    <% end %>
<% else %>
    <h4 class="no_match">No results match this search, sorry!</h4>
<% end %>

app/views/characters/_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<%= f.input :medium_id, collection: get_media_options, include_blank: true, input_html: { class: 'browser-default responsive_search' }, placeholder: "Select the media this character is from..." %>
<%= f.input :image, label_html: { class: 'active' }, as: :file, input_html: { class: "upload_button", data_direct_upload_url: rails_direct_uploads_url } %>
<%= f.input :hair_length, collection: Character::HAIR_LENGTHS, include_blank: true, input_html: { class: 'browser-default' } %>
<%= f.input :hair_color, label_html: { class: 'active' } %>
<%= f.input :eye_color, label_html: { class: 'active' } %>

app/views/characters/_filters.html.erb
<div>
   <%= form_with url: characters_path, method: :get, local: true, class: "search_wrapper_outer" do %>
   <div class="search_wrapper">
        <%= text_field_tag :query,
            params[:query],
            placeholder: "Search characters...",
            class: "search_input" %>
   </div>

    <%# Preserve existing filters when searching %>
    <%= hidden_field_tag :hair_length, params[:hair_length] if params[:hair_length].present? %>
    <%= hidden_field_tag :hair_color, params[:hair_color] if params[:hair_color].present? %>
    <%= hidden_field_tag :eye_color, params[:eye_color] if params[:eye_color].present? %>

    <%= submit_tag "Search", class: "search_button" %>
    <% end %>

    <%= link_to "Clear Search",
        characters_path(request.query_parameters.except(:query)),
        class: "clear_search" if params[:query].present? %> 
</div>

<div class="filter_container">
    <p class="filter_title">Filter by Hair Length: </p>
    <% ["short", "bob", "medium", "long", "none"].each do |hair_length| %>
        <%= link_to hair_length.capitalize,
            characters_path(request.query_parameters.merge(hair_length: hair_length)),
            class: "filter_button #{'active' if params[:hair_length] == hair_length}" %>
    <% end %>

    <%= link_to "Clear Filter",
        characters_path(request.query_parameters.except(:hair_length)),
        class: "filter_button" %>
</div>
<div class="filter_container">
    <p class="filter_title">Filter by Hair Color: </p>
    <% ["Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Purple", "Pink", "White"].each do |color| %>
    <%= link_to color.capitalize,
        characters_path(request.query_parameters.merge(hair_color: color)),
        class: "filter_button #{'active' if params[:hair_color] == color}" %>
    <% end %>

    <%= link_to "Clear Filter",
        characters_path(request.query_parameters.except(:hair_color)),
        class: "filter_button" %>
</div>
<div class="filter_container">
    <p class="filter_title">Filter by Eye Color: </p>
    <% ["Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Purple", "Pink", "White"].each do |color| %>
    <%= link_to color.capitalize,
        characters_path(request.query_parameters.merge(eye_color: color)),
        class: "filter_button #{'active' if params[:eye_color] == color}" %>
    <% end %>

    <%= link_to "Clear Filter",
        characters_path(request.query_parameters.except(:eye_color)),
        class: "filter_button" %>
</div>

app/views/characters/_saved_items.html.erb
<% if @added_items.any? %>
    <h4>Items</h4>
    <% for item in @added_items %>
    <div class="col s4">
        <div class="card small">
            <div class="card-image list_card">
                <% if item.image.attached? %>
                    <%= image_tag item.image, class: "list_img" %>
                <% else %>
                    <%= image_tag "photo_placeholder.jpg", class: "list_img" %>
                <% end %>
            </div>
            <div class="card-content">
                <span class="card-title"><%= link_to "#{item.name}", item_path(item) %></span>
                <p><%= link_to "#{item.store} ($#{item.price})", item.item_link, target: "_blank" %></p>
            </div>
        </div>
    </div>
    <% end %>
<% end %>

app/views/characters/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @character, 
                                                        type_of_form: "Edit Character",
                                                        fields: "characters/fields"} %>

app/views/characters/index.html.erb
<%= render partial: "partials/card_index_structure", locals: {model_name: "character", 
                                                       primary: "characters_list",
                                                       not_save: true,
                                                       filters: true,
                                                       filter_page: "characters/filters"} %>

app/views/characters/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @character, 
                                                        type_of_form: "New Character",
                                                        fields: "characters/fields"} %>

app/views/characters/show.html.erb
<%= render partial: "partials/card_show_structure", locals: {model_name: "character", 
                                                         object: @character,
                                                         primary: "character_data", 
                                                         association_card: "characters/saved_items"} %>