config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Regular HTML routes
  get "home", to: "home#index", as: "home"
  get "home/about", to: "home#about", as: "about"
  # get "error_404", to: "errors#not_found", as: "error_404"

  # Session management routes
  resources :sessions, only: [ :new, :create, :destroy ]
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  resources :users
  resources :media, except: [ :destroy ]
  resources :characters, except: [ :destroy ]
  resources :items
  resources :user_items, except: [ :show ]
  resources :user_media, except: [ :show, :edit, :update ]
  resources :user_characters, except: [ :show, :edit, :update ]
  resources :character_items, only: [ :new, :create, :destroy ]

  # Defines the root path route ("/")
  root "home#index"
end

app/models/item.rb
class Item < ApplicationRecord
  include Helpers::Deletions
  include Helpers::Activeable::InstanceMethods
  extend Helpers::Activeable::ClassMethods

  # Relationships
  has_many :user_items
  has_many :users, through: :user_items

  has_many :character_items
  has_many :characters, through: :character_items
  has_one_attached :image

  # Enum for category
  enum :category, { clothing: 1, accessory: 2, prop: 3, wig: 4, contacts: 5, makeup: 6, hat: 7 }, scopes: true, suffix: true

  # For category dropdown
  CATEGORIES = [ [ "Clothing", "clothing" ], [ "Accessory", "accessory" ], [ "Prop", "prop" ], [ "Wig", "wig" ], [ "Contacts", "contacts" ], [ "Makeup", "makeup" ], [ "Hat", "hat" ] ].freeze

  # Scopes
  scope :alphabetical, -> { order(:name) }
  scope :search, ->(term) { where("items.name ILIKE ?", "%#{term}%").order("items.name") }
  scope :by_category, ->(category) { where(category: category) }

  # Validations
  validates_presence_of :name
  validates_presence_of :category
  validates :item_link, presence: true, uniqueness: { case_sensitive: true }
  validates_presence_of :store
  validates_presence_of :price
  validates_inclusion_of :category, in: %w[clothing accessory prop wig contacts makeup hat], message: "is not a recognized category in the system"
  validates_format_of :item_link, with: /\A((https?:\/\/)|(www.))([^@\s,;]+)\.(com|edu|org|net|gov|mil|biz|info|us|uk)(\/[^@\s,;]+)*\z/i, message: "is not a valid format"
  validates_numericality_of :price, greater_than_or_equal_to: 0
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [ :show, :edit, :update, :destroy ]
  before_action :check_login, only: [ :new, :create, :edit, :update, :destroy ]
  authorize_resource

  # GET /items
  def index
    @items = Item.alphabetical
    if params[:query].present?
      @items = @items.search(params[:query])
    end
    if params[:status].present?
      @items = @items.active
    end
    if params[:category].present?
      @items = @items.by_category(params[:category])
    end
  end

  # GET /items/1
  def show
    @is_saved = false
    if current_user
      @is_saved = current_user.items.exists?(@item.id)
      @user_item = current_user.user_items.find_by(item_id: @item.id)
    end
    @average = UserItem.where(item_id: @item.id).average(:rating)
    if @average
      @average = @average.round
    end
    @reviews = UserItem.where(item_id: @item.id).where.not(review: [ nil, "" ]).order(created_at: :desc)
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to item_path(@item), notice: "Item was successfully created in the system."
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to item_path(@item), notice: "#{@item.name} was successfully updated in the system."
    else
      render :edit
    end
  end

  def destroy
    @item.make_inactive
    # Items cannot be fully destroyed, but can be set to inactive if out of stock or equivalent
    redirect_to items_path, notice: "#{@item.name} was successfully made inactive in the system."
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :store, :image, :item_link, :price, :category, :active)
  end
end

app/views/items/_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<%= f.input :store, label_html: { class: 'active' } %>
<%= f.input :image, label_html: { class: 'active' }, as: :file, input_html: { class: "upload_button", data_direct_upload_url: rails_direct_uploads_url } %>
<%= f.input :item_link, label_html: { class: 'active' } %>
<%= f.input :price, label_html: { class: 'active' } %>
<%= f.input :category, collection: Item::CATEGORIES, include_blank: true, input_html: { class: 'browser-default' } %>
<%# Materialize seemed to not work for this element so custom styling was needed %>
<div class="purchased-field">
  <label for="visible_checkbox2" class="purchased-label">Active</label>
  <%= f.input :active, label: false, input_html: { id: "visible_checkbox2" } %>
</div>

app/views/items/_filters.html.erb
<div>
   <%= form_with url: items_path, method: :get, local: true, class: "search_wrapper_outer" do %>
   <div class="search_wrapper">
        <%= text_field_tag :query,
            params[:query],
            placeholder: "Search items...",
            class: "search_input" %>
   </div>

    <%= submit_tag "Search", class: "search_button" %>
    <% end %>

    <%= link_to "Clear Search",
        items_path(request.query_parameters.except(:query)),
        class: "clear_search" if params[:query].present? %> 
</div>
<div class="filter_container">
    <p class="filter_title">Filter by Item Type: </p>
    <% ["clothing", "accessory", "prop", "wig", "contacts", "makeup", "hat"].each do |category| %>
        <%= link_to category.capitalize,
            items_path(request.query_parameters.merge(category: category)),
            class: "filter_button #{'active' if params[:category] == category}" %>
    <% end %>

    <%= link_to "Clear Filter",
        items_path(request.query_parameters.except(:category)),
        class: "filter_button" %>
</div>
<div class="filter_container" id="item_stock_filter">
    <p class="filter_title">Filter by Status: </p>
    <%= link_to "Only In Stock Items",
        items_path(request.query_parameters.merge(status: "active")),
        class: "filter_button #{'active' if params[:status] == "active"}" %>

    <%= link_to "Clear Filter",
        items_path(request.query_parameters.except(:status)),
        class: "filter_button" %>
</div>

app/views/items/_item_data.html.erb
<div class="card">
    <div class="card-content">
        <% if @item.image.attached? && @item.active %>
            <%= image_tag @item.image, class: "data-img" %>
            <h4><%= @item.name %></h4><br />
        <% elsif @item.image.attached? %>
            <%= image_tag @item.image, class: "data-img inactive-img" %>
            <h4><%= @item.name %> (Inactive Item)</h4>
            <p>This item is sold out or otherwise not currently available for purchase. Contact admin to have it's activity reinstated.</p><br />
        <% end %>
        <% if @average %>
            <% for i in 1..@average.to_i %>
                <i class="material-icons">star</i>
            <% end %>
            <% for j in 1..(5 - @average.to_i) %>
                <i class="material-icons">star_border</i>
            <% end %>
            <br />
        <% else %>
            <b>No User Ratings Yet</b><br />
        <% end %>
        <p>&nbsp;</p>
        <b>Store: <%= @item.store %></b><br />
        <b>Price: $<%= @item.price %></b><br />
        <b>Category: <%= @item.category.capitalize %></b><br />
        <p>&nbsp;</p>
        <% if @is_saved %>
            <%= button_to user_item_path(@user_item), method: :delete, data: { turbo_confirm: 'Are you sure you wish to delete this information?' }, class: 'waves-effect waves-pink btn btn-alert' do %>
                <b>Remove from Saves</b>
            <% end %>
            <% if @user_item.purchased %>
                <%= link_to edit_user_item_path(@user_item), class: 'waves-effect waves-pink btn btn-alert' do %>
                    <b>Add a Review</b>
                <% end %>
            <% end %>
        <% elsif logged_in? %>
            <b><%= button_to 'Save This Item', new_user_item_path, method: :get, params: { item_id: @item.id }, class: 'waves-effect waves-pink btn' %></b><br />
        <% end %>
        <% if logged_in? %>
            <p>&nbsp;</p>
            <b><%= button_to 'Add this Item to a Character', new_character_item_path, method: :get, params: { item_id: @item.id }, class: 'waves-effect waves-pink btn' %></b><br />
        <% end %>

        <div class="card-action">
            <a href="<%= @item.item_link %>" target="_blank" class="blue-text">View in Store</a>
        </div>
    </div>
</div>
<% if @reviews.any? %>
    <div class="card">
        <div class="card-content">
            <h4>Reviews</h4>
            <ul class="collection">
                <% for review in @reviews %>
                <li class="collection-item">"<%= review.review %>" - @<%= review.user.username %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/items/_items_list.html.erb
<% if @items.any?%>
    <% for item in @items %>
    <div class="col s4">
        <div class="card small">
            <div class="card-image list_card">
                <% if item.image.attached? && item.active %>
                    <%= image_tag item.image, class: "list_img" %>
                <% elsif item.image.attached? %>
                    <%= image_tag item.image, class: "list_img inactive-img" %>
                <% else %>
                    <%= image_tag "photo_placeholder.jpg", class: "list_img" %>
                <% end %>
            </div>
            <div class="card-content">
                <% if item.active %>
                    <span class="card-title"><%= link_to truncate(item.name, length: 22, omission: "..."), item_path(item) %></span>
                <% else %>
                    <span class="card-title"><%= link_to "#{truncate(item.name, length: 11, omission: "...")} (Inactive)", item_path(item) %></span>
                <% end %>
                <p><%= link_to "#{truncate(item.store, length: 15, omission: "...")} ($#{item.price})", item.item_link, target: "_blank" %></p>
            </div>
        </div>
    </div>
    <% end %>
<% else %>
    <h4 class="no_match">No results match this search, sorry!</h4>
<% end %>

app/views/items/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @item, 
                                                        type_of_form: "Edit Item",
                                                        fields: "items/fields"} %>

app/views/items/index.html.erb
<%= render partial: "partials/card_index_structure", locals: {model_name: "item", 
                                                       primary: "items_list",
                                                       not_save: true,
                                                       filters: true,
                                                       filter_page: "items/filters"} %>

app/views/items/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @item, 
                                                        type_of_form: "New Item",
                                                        fields: "items/fields"} %>

app/views/items/show.html.erb
<%= render partial: "partials/show_structure", locals: {model_name: "item", 
                                                         object: @item,
                                                         primary: "item_data", 
                                                         secondary: nil,
                                                         sidebar: nil} %>